# Generated by Django 2.1.7 on 2020-07-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='banks',
            new_name='bank',
        ),
    ]
