# Generated by Django 2.1.7 on 2020-07-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20200702_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank',
            new_name='banks',
        ),
    ]
